language: generic
sudo: required
services:
    - docker

before_installL:
    - docker build -t farhanadis/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true farhanadis/docker-react npm run test -- --coverage