language: generic
sudo: required
services:
    - docker

before_installL:
    - docker build -t farhanadis/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true farhanadis/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker-aws"
    env: "DockerAws-env"
    bucket_name: "elasticbeanstalk-us-west-2-679136563185"
    bucket_path: "docker-aws"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY